### ISSUE TITLE
您的loss我不是很能看得懂，想请您指教一下

### ISSUE THREAD

**Issue by HelloNicoo** [seukgcode/FastRE#2]
![image](https://user-images.githubusercontent.com/42365353/195358137-c94edb8f-68ee-4def-bc89-6daea7836dda.png)
![image](https://user-images.githubusercontent.com/42365353/195358262-da5f25bf-1e1f-4b7b-9796-c0f2bc4e3fa0.png)
您论文里的loss和代码里的loss我没办法联系起来，想请您解答一下

**Comment by 1iguozheng** [comment]
本质上就是对于文本中的每一个位置，都有一个AT类型作为所有类型的阈值标准，让所有的应该标注为1的位置的得分都大于相对应的AT的得分，而所有标注为0的位置的得分都小于相对应的AT的得分，也就是AT的值是一个标准。
和这篇论文的思路很像，这一篇会比较好理解一点，然后我们的代码也是参考这篇论文的代码实现来的：
https://arxiv.org/abs/2010.11304
