### ISSUE TITLE
Inference batch size

### ISSUE THREAD

**Issue by Sherryran08** [seukgcode/FastRE#3]
想请教一下作者的FastRe模型在推理的时候怎么实现batch size = 8进行推理的，谢谢解答！

**Comment by 1iguozheng** [comment]
这里没有提供并行的代码，但是比较容易修改，在extract items函数里一次传入多个文本，处理成张量得到所有的头实体，接下来就可以当作batch size为1的时候进行相同的处理了。直观地说，目前这个方法只能在头实体的预测中可以具有并行性，而在尾实体的预测中，仍然需要针对每一个头实体进行预测，这也是和训练阶段的过程一致的。不过第一部分的并行预测也是可以看到明显的速度提升的，而整个解码过程其实占了比较长的时间，模型的运算时间其实是比较短的。
